"""add updated_by to lgas and timeline_events

Revision ID: 3bf214fc796e
Revises: 6c9d9d92dfe4
Create Date: 2026-09-29 04:12:16.167855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf214fc796e'
down_revision: Union[str, Sequence[str], None] = '6c9d9d92dfe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lgas', sa.Column('updated_by', sa.String(), nullable=True))
    op.add_column('timeline_events', sa.Column('updated_by', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timeline_events', 'updated_by')
    op.drop_column('lgas', 'updated_by')
    # ### end Alembic commands ###
