"""create timeline_events table

Revision ID: 6c9d9d92dfe4
Revises: 8f07c8fd2528
Create Date: 2026-09-28 22:30:46.906072

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c9d9d92dfe4'
down_revision: Union[str, Sequence[str], None] = '8f07c8fd2528'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date_display', sa.String(), nullable=False),
    sa.Column('date_start', sa.String(), nullable=False),
    sa.Column('date_end', sa.String(), nullable=True),
    sa.Column('date_precision', sa.String(), nullable=True),
    sa.Column('date_basis', sa.Text(), nullable=True),
    sa.Column('event_title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('evidence_type', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('source_link', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('claim_source_map', sa.Text(), nullable=True),
    sa.Column('unconfirmed_details', sa.Text(), nullable=True),
    sa.Column('claims_and_disputes', sa.Text(), nullable=True),
    sa.Column('notes_limitations', sa.Text(), nullable=True),
    sa.Column('additional_sources', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_date_start'), 'timeline_events', ['date_start'], unique=False)
    op.create_index(op.f('ix_timeline_events_verification_status'), 'timeline_events', ['verification_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_events_verification_status'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_date_start'), table_name='timeline_events')
    op.drop_table('timeline_events')
    # ### end Alembic commands ###
