"""create homepage content tables

Revision ID: 6fbd4fdce746
Revises: deb598b23c08
Create Date: 2026-09-30 17:32:18.727798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fbd4fdce746'
down_revision: Union[str, Sequence[str], None] = 'deb598b23c08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('homepage_hero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eyebrow', sa.String(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=False),
    sa.Column('primary_cta_label', sa.String(), nullable=False),
    sa.Column('primary_cta_href', sa.String(), nullable=False),
    sa.Column('secondary_cta_label', sa.String(), nullable=False),
    sa.Column('secondary_cta_href', sa.String(), nullable=False),
    sa.Column('facts', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('homepage_hero_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('placeholder_icon', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homepage_hero_images_position'), 'homepage_hero_images', ['position'], unique=False)
    op.create_table('homepage_landmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('placeholder_icon', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homepage_landmarks_position'), 'homepage_landmarks', ['position'], unique=False)
    op.create_table('homepage_leaders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homepage_leaders_position'), 'homepage_leaders', ['position'], unique=False)
    op.create_table('homepage_moments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('is_anchor', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('placeholder_icon', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_homepage_moments_position'), 'homepage_moments', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_homepage_moments_position'), table_name='homepage_moments')
    op.drop_table('homepage_moments')
    op.drop_index(op.f('ix_homepage_leaders_position'), table_name='homepage_leaders')
    op.drop_table('homepage_leaders')
    op.drop_index(op.f('ix_homepage_landmarks_position'), table_name='homepage_landmarks')
    op.drop_table('homepage_landmarks')
    op.drop_index(op.f('ix_homepage_hero_images_position'), table_name='homepage_hero_images')
    op.drop_table('homepage_hero_images')
    op.drop_table('homepage_hero')
    # ### end Alembic commands ###
