"""add created_by to assets

Revision ID: 8600e675dded
Revises: df4d21161f13
Create Date: 2026-09-28 18:02:57.997849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8600e675dded'
down_revision: Union[str, Sequence[str], None] = 'df4d21161f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('created_by', sa.String(), nullable=True))
    op.create_index(op.f('ix_assets_created_by'), 'assets', ['created_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_created_by'), table_name='assets')
    op.drop_column('assets', 'created_by')
    # ### end Alembic commands ###
