"""create lgas table

Revision ID: 8f07c8fd2528
Revises: b7248a6c19a1
Create Date: 2026-09-28 22:18:56.909662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f07c8fd2528'
down_revision: Union[str, Sequence[str], None] = 'b7248a6c19a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lgas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('lga_name', sa.String(), nullable=False),
    sa.Column('headquarters', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('coordinate_type', sa.String(), nullable=True),
    sa.Column('major_towns_communities', sa.Text(), nullable=True),
    sa.Column('notable_places', sa.Text(), nullable=True),
    sa.Column('important_institutions', sa.Text(), nullable=True),
    sa.Column('source_1_name', sa.String(), nullable=True),
    sa.Column('source_1_type', sa.String(), nullable=True),
    sa.Column('source_1_link', sa.String(), nullable=True),
    sa.Column('source_2_name', sa.String(), nullable=True),
    sa.Column('source_2_type', sa.String(), nullable=True),
    sa.Column('source_2_link', sa.String(), nullable=True),
    sa.Column('source_3_name', sa.String(), nullable=True),
    sa.Column('source_3_type', sa.String(), nullable=True),
    sa.Column('source_3_link', sa.String(), nullable=True),
    sa.Column('source_date', sa.String(), nullable=True),
    sa.Column('last_checked', sa.String(), nullable=False),
    sa.Column('verification_status', sa.String(), nullable=False),
    sa.Column('limitations', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lgas_slug'), 'lgas', ['slug'], unique=True)
    op.create_index(op.f('ix_lgas_verification_status'), 'lgas', ['verification_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lgas_verification_status'), table_name='lgas')
    op.drop_index(op.f('ix_lgas_slug'), table_name='lgas')
    op.drop_table('lgas')
    # ### end Alembic commands ###
