"""add image_url to lgas

Revision ID: deb598b23c08
Revises: 3bf214fc796e
Create Date: 2026-09-30 07:30:51.643963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deb598b23c08'
down_revision: Union[str, Sequence[str], None] = '3bf214fc796e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lgas', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lgas', 'image_url')
    # ### end Alembic commands ###
